# This model is a reproduction with some small changes of our winning algorithm in the Calgary-Campinas challenge
# at MIDL2020. It has an improved sensitivity estimation and better metric logging capabilities based on DIRECT v0.2
# features.
physics:
    forward_operator: fft2(centered=False)
    backward_operator: ifft2(centered=False)
model:
    model_name: rim.rim.RIM
    hidden_channels: 128
    image_initialization: sense  # This uses the computed sensitivity map to create a zero-filled reconstruction
    length: 16
    depth: 2
    steps: 1
    no_parameter_sharing: false
    instance_norm: false
    dense_connect: false
    replication_padding: true
logging:
    tensorboard:
        num_images: 4
inference:
    batch_size: 8
    dataset:
        name: TECFIDERA
        text_description: inference
        transforms:
            crop: null
            estimate_sensitivity_maps: true
            scaling_key: masked_kspace
